#!/usr/bin/env bash
# Create a 404 error page
sudo apt-get update
sudo apt-get install -y nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
echo "" >> /usr/share/nginx/custom_404.html
sudo sed -i '44i\	 error_page 404 /custom_404.html;\n		location = /custom_404.html {\n			root /usr/share/nginx/html;\n			internal;\n		}' /etc/nginx/sites-enabled/default
sudo sed -i '36i\               rewrite ^/redirect_me https://www.youtube.com/watch?v=bfrP4MEXawA permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start
