#!/usr/bin/env bash
# Create a 404 error page
sudo apt-get update
sudo apt-get install -y nginx
echo "Ceci n'est pas une page" | sudo tee /etc/share/nginx/html/custom_404.html
sudo sed -i '26i\ error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-enabled/default
sudo service nginx start
