#!/usr/bin/env bash
# createas a file containing it's PID, prints different messages for different signals
echo $$ > /var/run/holbertonscript.pid
while true; do
      echo "To infinity and beyond"
      trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit;' TERM
      trap 'echo "Y U no love me?!"; rm /var/run/holbertonscript.pid; exit;' INT
      sleep 2
done
