#!/usr/bin/env bash
# run nginx as user nginx
pkill apache2
sed -i 's/80 default/8080 default/g' /etc/nginx/sites-enabled/default
chmod 755 /etc/nginx/nginx.conf
find / -name "*nginx*" | chown -R nginx
su nginx -c nginx
