#!/usr/bin/env bash
# run nginx as user nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/ /var/log/nginx /usr/share/nginx/
chmod 755 /etc/nginx/nginx.conf
su nginx -c nginx
