#!/usr/bin/env bash
# Use awk && bash function to print info on subdomains

print_info ()
{
    printf "The subdomain %s is a " "$1"
    RECORD=`dig "$1"."$2" | grep -A1 "ANSWER SECTION:" | grep "$2" | awk -F' ' '{print $4}'`
    printf "%s record and points to " "$RECORD"
    dig "$1"."$2" | grep -A1 "ANSWER SECTION:" | grep "$2" | awk -F' ' '{print $5}'
	return 0
}

if (($# == 2)); then
    print_info "$2" "$1"
else
    for sub in "www" "lb-01" "web-01" "web-02"
    do
	print_info "$sub" "$1"
    done
fi
