#!/usr/bin/env bash
# give nginx a custom header based on the host servers name
sudo apt-get update
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i "11i\add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
