#!/usr/bin/env bash
# Setup a load balancer connected to two other servers
sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
sudo sed -i '$a\\nlisten appname 0.0.0.0:80\n\tmode http\n\tstats enable' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tserver 67-web-01 54.90.179.127:80\n\tserver 67-web-02 52.201.241.151:80' /etc/haproxy/haproxy.cfg
sudo service haproxy start
