#!/usr/bin/env bash
# This script will display Holberton School 10 times, but the 9th time it says hi instead

((i=0))
while ((i < 10)); do
      echo "Holberton School"
      if ((i == 8)); then echo "Hi"; fi
      ((i++))
done
