#!/usr/bin/env bash
# Displays hours 0-12, for each hour display 1-59

((hour=0))
while ((hour <= 12)); do
    ((minute=1))
    echo "Hour: $hour"
    while ((minute < 60)); do
      	echo "$minute"
	((minute++))
    done
    ((hour++))
done
