#!/usr/bin/env bash
# Setup nginx to listen to port 80
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[\:\:\]\:8080/listen \[\:\:\]\:80/g' /etc/nginx/sites-enableddefault
service nginx restart
