#!/usr/bin/env bash
# Displays 1-100, for multiples of 3 prints Fizz, for multiples of 5 print Buzz, for a multiple of 15 print FizzBuzz

for ((i = 1; i <= 100; i++)); do
    if ((i % 15 == 0)); then echo "FizzBuzz";
    elif ((i % 5 == 0)); then echo "Buzz";
    elif ((i % 3 == 0)); then echo "Fizz";
    else echo "$i";
    fi
done
