#!/usr/bin/env bash
# Display 1-20, for 4 display bad luck from China, for 9 display bad luck from Japan, for 17 display bad luck from Italy

((i = 1))
while ((i <= 20)); do
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck form Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$i"
	    ;;
    esac
      ((i++))
done
