#!/usr/bin/env bash
# Display 1-20, for 4 display bad luck from China, for 9 display bad luck from Japan, for 17 display bad luck from Italy

((i = 1))
while ((i <= 20)); do
      if ((i == 4)); then echo "bad luck from China";
      elif ((i == 9)); then echo "bad luck from Japan";
      elif ((i == 17)); then echo "bad luck from Italy";
      else echo "$i"; fi
      ((i++))
done
